const DEFAULT_SUBSCRIPTION_PLANS = [
  {
    slug: 'free',
    name: 'Free',
    description: 'Kucuk projeler icin ideal baslangic paketi',
    price: 0,
    billingType: 'fixed',
    userLimit: 2,
    ownerLimit: 1,
    storageLimit: 500 * 1024 * 1024,
    monthlyRequestLimit: 1000,
    pricePerGBStorage: 0,
    pricePerThousandRequests: 0,
    isActive: true,
    sortOrder: 1,
  },
  {
    slug: 'pro',
    name: 'Pro',
    description: 'Buyuyen ekipler icin guclu cozum',
    price: 5,
    billingType: 'fixed',
    userLimit: 10,
    ownerLimit: 5,
    storageLimit: 5 * 1024 * 1024 * 1024,
    monthlyRequestLimit: 10000,
    pricePerGBStorage: 0,
    pricePerThousandRequests: 0,
    isActive: true,
    sortOrder: 2,
  },
  {
    slug: 'promax',
    name: 'Pro Max',
    description: 'Profesyonel ekipler icin sinirsiz guc',
    price: 12,
    billingType: 'fixed',
    userLimit: null,
    ownerLimit: null,
    storageLimit: 10 * 1024 * 1024 * 1024,
    monthlyRequestLimit: 100000,
    pricePerGBStorage: 0,
    pricePerThousandRequests: 0,
    isActive: true,
    sortOrder: 3,
  },
  {
    slug: 'enterprise',
    name: 'Enterprise',
    description: 'Kullandiginiz kadar odeyin - kurumsal cozum',
    price: 0,
    billingType: 'usage-based',
    userLimit: null,
    ownerLimit: null,
    storageLimit: null,
    monthlyRequestLimit: null,
    pricePerGBStorage: 1,
    pricePerThousandRequests: 0.1,
    isActive: true,
    sortOrder: 4,
  },
];

module.exports = {
  DEFAULT_SUBSCRIPTION_PLANS,
};
