const GB = 1024 ** 3;
const MB = 1024 ** 2;

const DEFAULT_SUBSCRIPTION_PLANS = [
  {
    slug: 'free',
    name: 'Free',
    description: 'Tek bir tenant üzerinde ContextHub iş akışlarını keşfedin.',
    price: 0,
    billingType: 'fixed',
    userLimit: 1,
    ownerLimit: 1,
    storageLimit: 500 * MB,
    monthlyRequestLimit: 1000,
    features: [],
    marketing: { tagline: 'Tenant’ınızı keşfedin', audience: 'Deneme ve düşük trafikli tenant’lar', badge: '', featured: false },
    capabilities: [
      { key: 'content', label: 'Temel içerik yönetimi', description: 'İçerik, medya, menü ve form araçları' },
      { key: 'quota', label: 'Tek kullanıcı', description: 'Davet özelliği olmadan tek owner ile kullanım' },
      { key: 'support', label: 'Topluluk desteği', description: 'Dokümantasyon ve topluluk kanalları' },
    ],
    pricePerGBStorage: 0,
    pricePerThousandRequests: 0,
    isActive: true,
    sortOrder: 1,
  },
  {
    slug: 'pro',
    name: 'Pro',
    description: 'Üretimde çalışan bir tenant için ekip özellikleri ve kontrollü kapasite.',
    price: 12,
    billingType: 'fixed',
    userLimit: 5,
    ownerLimit: 2,
    storageLimit: 3 * GB,
    monthlyRequestLimit: 50000,
    features: [],
    marketing: { tagline: 'Tenant’ı üretime alın', audience: 'Üretim tenant’ları ve içerik ekipleri', badge: '', featured: false },
    capabilities: [
      { key: 'workflow', label: 'Ekip iş akışları', description: 'Rol, yayın ve webhook yönetimi' },
      { key: 'capacity', label: 'Üretim kapasitesi', description: 'Tenant başına 3 GB depolama ve 50 bin istek' },
      { key: 'support', label: 'E-posta desteği', description: '3 iş günü hedef yanıt süresi' },
    ],
    pricePerGBStorage: 0,
    pricePerThousandRequests: 0,
    isActive: true,
    sortOrder: 2,
  },
  {
    slug: 'promax',
    name: 'Pro Max',
    description: 'Yüksek trafikli veya geniş ekipli tek bir tenant için artırılmış kapasite.',
    price: 45,
    billingType: 'fixed',
    userLimit: null,
    ownerLimit: 5,
    storageLimit: 5 * GB,
    monthlyRequestLimit: 150000,
    features: [],
    marketing: { tagline: 'Tenant’ı ölçekleyin', audience: 'Yüksek trafikli ve geniş ekipli tenant’lar', badge: 'En popüler', featured: true },
    capabilities: [
      { key: 'capacity', label: 'Yüksek tenant kapasitesi', description: 'Tenant başına 5 GB depolama ve 150 bin istek' },
      { key: 'users', label: 'Sınırsız kullanıcı', description: 'Tenant ekibini kullanıcı başı ücret olmadan büyütün' },
      { key: 'support', label: 'Öncelikli destek', description: '1 iş günü hedef yanıt süresi' },
    ],
    pricePerGBStorage: 0,
    pricePerThousandRequests: 0,
    isActive: true,
    sortOrder: 3,
  },
  {
    slug: 'enterprise',
    name: 'Enterprise',
    description: 'Özel kapasite, güvenlik ve hizmet seviyesi gerektiren kurumlar için sözleşmeli paket.',
    price: 250,
    billingType: 'fixed',
    userLimit: null,
    ownerLimit: null,
    storageLimit: null,
    monthlyRequestLimit: null,
    features: [],
    marketing: { tagline: 'Birlikte tasarla', audience: 'Kurumsal ekipler', badge: 'Teklif', featured: false },
    capabilities: [
      { key: 'capacity', label: 'Özel tenant kapasitesi', description: 'Sözleşmeye göre trafik, depolama ve ekip limiti' },
      { key: 'sla', label: 'SLA ve öncelikli destek', description: 'İhtiyaca göre hizmet seviyesi' },
      { key: 'security', label: 'Kurumsal güvenlik', description: 'DPA ve özel güvenlik gereksinimleri' },
    ],
    pricePerGBStorage: 0,
    pricePerThousandRequests: 0,
    isActive: true,
    sortOrder: 4,
  },
];

const DEFAULT_PLAN_PRICES = [
  { key: 'free.manual.month.usd', planSlug: 'free', provider: 'manual', interval: 'month', currency: 'USD', amountMinor: 0 },
  { key: 'pro.paddle.month.usd', planSlug: 'pro', provider: 'paddle', interval: 'month', currency: 'USD', amountMinor: 1200, envKey: 'PADDLE_PRICE_PRO_MONTH' },
  { key: 'pro.paddle.year.usd', planSlug: 'pro', provider: 'paddle', interval: 'year', currency: 'USD', amountMinor: 13200, envKey: 'PADDLE_PRICE_PRO_YEAR' },
  { key: 'promax.paddle.month.usd', planSlug: 'promax', provider: 'paddle', interval: 'month', currency: 'USD', amountMinor: 4500, envKey: 'PADDLE_PRICE_PROMAX_MONTH' },
  { key: 'promax.paddle.year.usd', planSlug: 'promax', provider: 'paddle', interval: 'year', currency: 'USD', amountMinor: 45000, envKey: 'PADDLE_PRICE_PROMAX_YEAR' },
];

module.exports = {
  DEFAULT_SUBSCRIPTION_PLANS,
  DEFAULT_PLAN_PRICES,
};
