import { PERMISSIONS } from './permissions.js'

export const PERMISSION_LABELS = {
  [PERMISSIONS.DASHBOARD_VIEW]: 'Kontrol panelini görüntüle',
  [PERMISSIONS.USERS_VIEW]: 'Kullanıcıları görüntüle',
  [PERMISSIONS.USERS_CREATE]: 'Kullanıcı oluştur',
  [PERMISSIONS.USERS_UPDATE]: 'Kullanıcı güncelle',
  [PERMISSIONS.USERS_DELETE]: 'Kullanıcı sil',
  [PERMISSIONS.USERS_INVITE]: 'Kullanıcı davet et',
  [PERMISSIONS.USERS_ASSIGN_ROLE]: 'Kullanıcı rolü ata',
  [PERMISSIONS.USERS_MANAGE]: 'Kullanıcıları tamamen yönet',
  [PERMISSIONS.ROLES_VIEW]: 'Rolleri görüntüle',
  [PERMISSIONS.ROLES_CREATE]: 'Rol oluştur',
  [PERMISSIONS.ROLES_UPDATE]: 'Rol güncelle',
  [PERMISSIONS.ROLES_DELETE]: 'Rol sil',
  [PERMISSIONS.ROLES_MANAGE]: 'Rolleri tamamen yönet',
  [PERMISSIONS.PROFILE_UPDATE]: 'Profilini güncelle',
  [PERMISSIONS.TENANTS_VIEW]: 'Varlıkları görüntüle',
  [PERMISSIONS.TENANTS_CREATE]: 'Varlık oluştur',
  [PERMISSIONS.TENANTS_UPDATE]: 'Varlık güncelle',
  [PERMISSIONS.TENANTS_DELETE]: 'Varlık sil',
  [PERMISSIONS.TENANTS_MANAGE]: 'Varlıkları tamamen yönet',
  [PERMISSIONS.CONTENT_VIEW]: 'İçerikleri görüntüle',
  [PERMISSIONS.CONTENT_CREATE]: 'İçerik oluştur',
  [PERMISSIONS.CONTENT_UPDATE]: 'İçerik güncelle',
  [PERMISSIONS.CONTENT_DELETE]: 'İçerik sil',
  [PERMISSIONS.CONTENT_MANAGE]: 'İçerikleri tamamen yönet',
  [PERMISSIONS.MEDIA_VIEW]: 'Medya öğelerini görüntüle',
  [PERMISSIONS.MEDIA_CREATE]: 'Medya yükle',
  [PERMISSIONS.MEDIA_UPDATE]: 'Medya güncelle',
  [PERMISSIONS.MEDIA_DELETE]: 'Medya sil',
  [PERMISSIONS.MEDIA_MANAGE]: 'Medya kütüphanesini tamamen yönet',
  [PERMISSIONS.CATEGORIES_VIEW]: 'Kategorileri görüntüle',
  [PERMISSIONS.CATEGORIES_CREATE]: 'Kategori oluştur',
  [PERMISSIONS.CATEGORIES_UPDATE]: 'Kategori güncelle',
  [PERMISSIONS.CATEGORIES_DELETE]: 'Kategori sil',
  [PERMISSIONS.CATEGORIES_MANAGE]: 'Kategorileri tamamen yönet',
  [PERMISSIONS.COLLECTIONS_VIEW]: 'Koleksiyonları görüntüle',
  [PERMISSIONS.COLLECTIONS_CREATE]: 'Koleksiyon oluştur',
  [PERMISSIONS.COLLECTIONS_UPDATE]: 'Koleksiyon güncelle',
  [PERMISSIONS.COLLECTIONS_DELETE]: 'Koleksiyon sil',
  [PERMISSIONS.COLLECTIONS_MANAGE]: 'Koleksiyonları tamamen yönet',
  [PERMISSIONS.FORMS_VIEW]: 'Formları görüntüle',
  [PERMISSIONS.FORMS_CREATE]: 'Form oluştur',
  [PERMISSIONS.FORMS_UPDATE]: 'Form güncelle',
  [PERMISSIONS.FORMS_DELETE]: 'Form sil',
  [PERMISSIONS.FORMS_MANAGE]: 'Formları tamamen yönet',
  [PERMISSIONS.PLACEMENTS_VIEW]: 'Placements görüntüle',
  [PERMISSIONS.PLACEMENTS_CREATE]: 'Placement oluştur',
  [PERMISSIONS.PLACEMENTS_UPDATE]: 'Placement güncelle',
  [PERMISSIONS.PLACEMENTS_DELETE]: 'Placement sil',
  [PERMISSIONS.PLACEMENTS_MANAGE]: 'Placements tamamen yönet',
  [PERMISSIONS.MENUS_VIEW]: 'Menüleri görüntüle',
  [PERMISSIONS.MENUS_CREATE]: 'Menü oluştur',
  [PERMISSIONS.MENUS_UPDATE]: 'Menü güncelle',
  [PERMISSIONS.MENUS_DELETE]: 'Menü sil',
  [PERMISSIONS.MENUS_MANAGE]: 'Menüleri tamamen yönet',
  [PERMISSIONS.ANALYTICS_VIEW]: 'Analitikleri görüntüle',
  [PERMISSIONS.SETTINGS_VIEW]: 'Ayarları görüntüle',
  [PERMISSIONS.SETTINGS_UPDATE]: 'Ayarları güncelle',
  [PERMISSIONS.SETTINGS_MANAGE]: 'Ayarları tamamen yönet'
}

export const PERMISSION_GROUP_LABELS = {
  DASHBOARD: 'Kontrol Paneli',
  USERS: 'Kullanıcı Yönetimi',
  ROLES: 'Roller',
  PROFILE: 'Profil',
  TENANTS: 'Varlıklar',
  CONTENT: 'İçerik',
  MEDIA: 'Medya',
  CATEGORIES: 'Kategoriler',
  COLLECTIONS: 'Koleksiyonlar',
  FORMS: 'Formlar',
  PLACEMENTS: 'Placements',
  MENUS: 'Menüler',
  ANALYTICS: 'Analitik',
  SETTINGS: 'Ayarlar'
}
